"""
This script was completely generated by Claude 3.5 to automate running transkun transcription.
"""



import pandas as pd
import os
import subprocess
import sys
from pathlib import Path

def process_audio_with_transkun(csv_file_path, output_midi_dir, audio_home_dir, transkun_command_template="transkun {input_audio} {output_midi}", skip_existing=True, timeout_minutes=15):
    """
    Process CSV file to convert audio files to MIDI using Transkun for split_encoded != 2
    
    Args:
        csv_file_path (str): Path to the input CSV file
        output_midi_dir (str): Directory to store generated MIDI files
        audio_home_dir (str): Home directory where audio files are located
        transkun_command_template (str): Template for the transkun command
        skip_existing (bool): If True, skip files that already have MIDI output
        timeout_minutes (int): Timeout in minutes for each file processing
    """
    
    # Create output directory if it doesn't exist
    os.makedirs(output_midi_dir, exist_ok=True)
    
    # Read the CSV file
    try:
        df = pd.read_csv(csv_file_path)
        print(f"Loaded CSV with {len(df)} rows")
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return
    
    # Check if required columns exist
    required_columns = ['orig_audio_filename', 'midi_id', 'split_encoded']
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        print(f"Error: Missing required columns: {missing_columns}")
        return
    
    # Filter rows where split_encoded != 2
    filtered_df = df[df['split_encoded'] != 2].copy()
    print(f"Found {len(filtered_df)} rows with split_encoded != 2")
    
    if len(filtered_df) == 0:
        print("No rows to process")
        return
    
    # Initialize the new column if it doesn't exist
    if 'transkun_filename' not in filtered_df.columns:
        filtered_df['transkun_filename'] = ''
    
    # Process each row
    processed_count = 0
    failed_count = 0
    skipped_count = 0
    
    for idx, row in filtered_df.iterrows():
        try:
            # Get the audio file path and midi_id
            audio_filename = row['orig_audio_filename']
            midi_id = str(row['midi_id'])
            
            # Create output MIDI filename
            output_midi_filename = f"{midi_id}.mid"
            output_midi_path = os.path.join(output_midi_dir, output_midi_filename)
            
            # Skip if MIDI file already exists and skip_existing is True
            if skip_existing and os.path.exists(output_midi_path):
                # Update the CSV record for consistency
                filtered_df.at[idx, 'transkun_filename'] = output_midi_filename
                print(f"⏭️  Skipping existing file: {output_midi_filename}")
                skipped_count += 1
                continue
            
            # Construct full path to audio file using home directory
            audio_file_path = os.path.join(audio_home_dir, audio_filename)
            
            # Check if audio file exists
            if not os.path.exists(audio_file_path):
                print(f"⚠️  Warning: Audio file not found: {audio_file_path}")
                failed_count += 1
                continue
            
            # Prepare the transkun command
            command = transkun_command_template.format(
                input_audio=audio_file_path,
                output_midi=output_midi_path
            )
            
            print(f"🎵 Processing {audio_filename} -> {output_midi_filename}")
            print(f"   Running command: {command}")
            
            # Run the transkun command
            result = subprocess.run(
                command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=timeout_minutes * 60  # Convert minutes to seconds
            )
            
            if result.returncode == 0:
                # Success - update the dataframe
                filtered_df.at[idx, 'transkun_filename'] = output_midi_filename
                processed_count += 1
                print(f"✅ Successfully processed: {output_midi_filename}")
            else:
                print(f"❌ Error processing {audio_filename}:")
                print(f"   Return code: {result.returncode}")
                print(f"   Stderr: {result.stderr}")
                failed_count += 1
                
        except subprocess.TimeoutExpired:
            print(f"⏰ Timeout ({timeout_minutes} min) processing {audio_filename}")
            print(f"   Consider increasing timeout or checking if this file is problematic")
            failed_count += 1
        except Exception as e:
            print(f"❌ Error processing {audio_filename}: {e}")
            failed_count += 1
    
    # Save the processed CSV
    output_csv_path = csv_file_path.replace('.csv', '_processed.csv')
    try:
        # Save only the processed rows back to the original dataframe structure
        # We need to update the original dataframe with our changes
        df.loc[filtered_df.index, 'transkun_filename'] = filtered_df['transkun_filename']
        df.to_csv(output_csv_path, index=False)
        
        print(f"\n📄 Saved processed CSV to: {output_csv_path}")
        print(f"✅ Successfully processed: {processed_count} files")
        print(f"⏭️  Skipped existing: {skipped_count} files")
        print(f"❌ Failed to process: {failed_count} files")
        print(f"📊 Total in filtered set: {len(filtered_df)} files")
        
    except Exception as e:
        print(f"Error saving processed CSV: {e}")

def resume_processing(csv_file_path, output_midi_dir, audio_home_dir, transkun_command_template="transkun {input_audio} {output_midi}"):
    """
    Resume processing by only processing files that failed or weren't processed yet
    """
    print("🔄 Resuming processing - will skip already processed files")
    process_audio_with_transkun(csv_file_path, output_midi_dir, audio_home_dir, transkun_command_template, skip_existing=True, timeout_minutes=TIMEOUT_MINUTES)

def force_reprocess_all(csv_file_path, output_midi_dir, audio_home_dir, transkun_command_template="transkun {input_audio} {output_midi}"):
    """
    Force reprocess all files (will overwrite existing MIDI files)
    """
    print("🔄 Force reprocessing all files - will overwrite existing files")
    process_audio_with_transkun(csv_file_path, output_midi_dir, audio_home_dir, transkun_command_template, skip_existing=False, timeout_minutes=TIMEOUT_MINUTES)

def show_processing_status(csv_file_path, output_midi_dir):
    """
    Show the current processing status
    """
    try:
        df = pd.read_csv(csv_file_path)
        filtered_df = df[df['split_encoded'] != 3]
        
        total_files = len(filtered_df)
        
        # Count actual MIDI files that exist
        midi_files_exist = 0
        for _, row in filtered_df.iterrows():
            midi_id = str(row['midi_id'])
            output_midi_filename = f"{midi_id}.mid"
            output_midi_path = os.path.join(output_midi_dir, output_midi_filename)
            if os.path.exists(output_midi_path):
                midi_files_exist += 1
        
        print(f"\n📊 Processing Status Report:")
        print(f"   Total files to process: {total_files}")
        print(f"   MIDI files that exist: {midi_files_exist}")
        print(f"   Files still to process: {total_files - midi_files_exist}")
        
        return total_files - midi_files_exist
        
    except Exception as e:
        print(f"Error checking status: {e}")
        return -1

# Timeout in minutes for each file (increase if files are taking too long)
TIMEOUT_MINUTES = 30

# ==========================================
# CONFIGURATION - EDIT THESE PATHS
# ==========================================

# Path to your CSV file
CSV_FILE_PATH = "processed_data.csv"

# Directory where audio files are located
AUDIO_HOME_DIRECTORY = "../maestro-v3.0.0/"

# Directory where generated MIDI files will be saved
OUTPUT_MIDI_DIRECTORY = "./transkun_midi"

# Transkun command template (usually no need to change this)
TRANSKUN_COMMAND = "transkun {input_audio} {output_midi}"

# ==========================================

def main():
    """
    Main function with options for different processing modes
    """
    print("🎵 Audio to MIDI Processing Script using Transkun")
    print("=" * 60)
    
    # Use the configured parameters
    csv_file = CSV_FILE_PATH
    audio_home_dir = AUDIO_HOME_DIRECTORY
    output_dir = OUTPUT_MIDI_DIRECTORY
    transkun_cmd = TRANSKUN_COMMAND
    timeout_min = TIMEOUT_MINUTES
    
    # Validate inputs
    if not os.path.exists(csv_file):
        print(f"❌ Error: CSV file not found: {csv_file}")
        print("Please update CSV_FILE_PATH in the script")
        return
    
    if not os.path.exists(audio_home_dir):
        print(f"❌ Error: Audio home directory not found: {audio_home_dir}")
        print("Please update AUDIO_HOME_DIRECTORY in the script")
        return
    
    print(f"⚙️  Configuration:")
    print(f"   CSV file: {csv_file}")
    print(f"   Audio home directory: {audio_home_dir}")
    print(f"   Output directory: {output_dir}")
    print(f"   Transkun command: {transkun_cmd}")
    print(f"   Timeout per file: {timeout_min} minutes")
    
    # Show current status
    remaining = show_processing_status(csv_file, output_dir)
    
    if remaining == 0:
        print("\n🎉 All files appear to be processed!")
        return
    elif remaining > 0:
        print(f"\n🔄 {remaining} files still need processing")
    
    # Check for command line arguments
    if len(sys.argv) > 1:
        mode = sys.argv[1].lower()
        if mode in ['resume', 'skip', 'continue']:
            print("\n🔄 Resuming processing (skipping existing files)...")
            resume_processing(csv_file, output_dir, audio_home_dir, transkun_cmd)
        elif mode in ['force', 'all', 'reprocess']:
            print("\n🔄 Force reprocessing all files...")
            force_reprocess_all(csv_file, output_dir, audio_home_dir, transkun_cmd)
        elif mode in ['status', 'check']:
            print("\n✅ Status check complete")
        else:
            print(f"\n❌ Unknown mode: {mode}")
            print("Available modes: resume, force, status")
    else:
        # Default behavior: resume processing
        print("\n🔄 Default: Resuming processing (skipping existing files)...")
        print("💡 Tip: Use 'python predict_midi.py resume' to skip existing files")
        print("💡 Tip: Use 'python predict_midi.py force' to reprocess all files")
        print("💡 Tip: Use 'python predict_midi.py status' to check status only")
        print(f"💡 Tip: Current timeout is {timeout_min} minutes per file")
        process_audio_with_transkun(csv_file, output_dir, audio_home_dir, transkun_cmd, skip_existing=True, timeout_minutes=timeout_min)

if __name__ == "__main__":
    main()